name = "backend"
compatibility_date = "2024-09-19"
compatibility_flags = [ "nodejs_compat" ]

 [vars]
"DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNjEyZWQ5OWMtZDAxNi00NWMzLThlZjUtNmFmYmU1NTk0ZGIyIiwidGVuYW50X2lkIjoiNTEyYjY1NWRmODdiOGU1MWQ4OTRmOTRjZTgwYTBmMzViMjJjYjU5ZjIyZDRlYjRjYzQxZjZhNTFhZWZiY2MyOSIsImludGVybmFsX3NlY3JldCI6ImEwN2RmOThjLTE0YTgtNDkwZi05ZDllLTg4ODQxZWI5NmNjNSJ9.-fdWm-eS58bH1PbhKTV5pMKCICyAN0obS6CcAF7fYyo""